### PR TITLE
Adds getnetworkhashps back.

### PR DESCRIPTION
**Pull request by iquidus**
getnetworkhashps had been removed. This adds it back.

### CODE REVIEW

**Comment by heavycoin** [comment]
This bit isn't right, as the Heavycoin difficulty can change every block on downward difficulty adjustments and every 5 blocks on upward.

``` C++
+    // If lookup is -1, then use blocks since last difficulty change.
+    if (lookup <= 0)
+        lookup = pb->nHeight % 2016 + 1;
```

How important is the lookup=-1 feature?  Is it used for anything?

**Comment by lzp729** [comment]
2016 is from litecoin... haha

lookup feature used to query "lookup" block and get or estimate nethashps of "height", correct.me if wrong...

**Comment by heavycoin** [comment]
Yes, but we wonder if we should care.  It depends if the -1 mode of operation is used anywhere.

**Comment by lzp729** [comment]
I just think we should keep the same interface and expected functionality as Bitcoin,  to get best RPCCall compatibility.

**Comment by lzp729** [comment]
Cheers.

Zhpool will be able to show nethashrate soon :)

**Pull request merged**
